name: USB Beamer Addon
slug: usb-beamer
startup: services
url: https://github.com/dlbogdan/hassio-usb-beamer-addon
panel_icon: mdi:usb
usbip: true
usb: true
kernel_modules: true
host_network: true
apparmor: false
version: 1.4.0
description: >
  USB Beamer Addon that allows you to use remote USB devices on your Hassio system.
  After starting the addon, a public key will be generated and displayed below.
  Copy this public key from here to the web GUI of the server(s) you want to access USB devices from.
init: false
full_access: true
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
schema:
  public_key: str
options:
  public_key: ""
