name: USB Beamer Addon
slug: usb-beamer
startup: services
url: https://github.com/dlbogdan/hassio-usb-beamer-addon
panel_icon: mdi:usb
usbip: true
usb: true
kernel_modules: true
host_network: true
apparmor: false
version: 1.4.18
description: >
  USB Beamer Addon that allows you to use remote USB devices on your Hassio system.
  On first start, a key pair is generated. Go to the 'Log' tab to find the public key.
  Copy the public key from the log and paste it into the web UI of your USB Beamer server(s).
init: false
full_access: true
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
schema: {}
options: {}
uart: true
udev: true
